version: "3.9"
services:
  web:
    build: .
    ports:
      - "10000:10000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - JWT_SECRET=dev-secret
      - PORT=10000
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
