server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:file:./data/kstocksim;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
